baseURL = "https://suam.wtf/"
title = "SUAM"
copyright = ""
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://www.facebook.com/photo.php?fbid=3303186886378184&set=a.540950052601895&type=3"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "SUAM Team"
  description = "มีสาระบ้างเดี๋ยวเขาหาว่าเอาแต่เมา"
  homepageImage = "/images/landing.png"
  share = false
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    email = ""
    facebook = ""
    twitter = ""
    linkedin = ""
    stack-overflow = ""
    instagram = ""
    github = ""
    weibo = ""
    medium = ""
    pinterest = ""
    reddit = ""
    gitlab = ""
    mastodon = ""
    keybase = ""

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
